### ISSUE TITLE
google drive problem: Access blocked: VisiData has not completed the Google verification process

### ISSUE THREAD

**Issue by maxim-uvarov** [visidata/vdplus#15]
hi:) 
I wanted to try visidata with google sheets, but got this error:
<img width="488" alt="image" src="https://github.com/visidata/vdplus/assets/4896754/769d3ba5-e252-47bc-97cd-bab3ab31ee05">

If it aligns with your priorities, maybe you can complete the Google verification. Alternatively, maybe you can provide the details of what needs to be changed in the code if I register my own developer application with Google Drive API access.

It is not an urgent need for me, just wanted to play with it.

**Comment by saulpw** [comment]
Hey @maxim-uvarov!  The code in this repo has been integrated into the main saulpw/visidata repo, and this repo is now defunct.  (I should remove/archive it shortly.)  I know the Google Drive code doesn't work for other people, at least for the issue you raise.  To be honest, I don't know right now what would have to be done to get it to work--it might have rotted a bit by now as well.

It's still in the saulpw/visidata:vdplus/api/google directory though (one of the last vestiges of vdplus), and if we got it working again, I'd love to migrate it into its proper place in the loaders directory.  I'd be happy to work with you if you're up for driving the process.

**Comment by maxim-uvarov** [comment]
Hey @saulpw, no worries. I use Google Sheets very infrequently, and I don't think VisiData can boost my productivity there very much, at least at this stage of life. Let's leave it until somebody really needs this feature.
