### ISSUE TITLE
vgit pip link is wrong

### ISSUE THREAD

**Issue by LaPingvino** [visidata/vdplus#4]
should be `pip3 install git+git://github.com/visidata/vdplus/vgit@develop`
(for me on Arch: `pip install git+git://github.com/visidata/vdplus/vgit@develop`)

**Comment by LaPingvino** [comment]
Realizing it will probably not work anyway because of access rights stuff xD

**Comment by saulpw** [comment]
Thanks @LaPingvino !  At least this is more accurate :)
